"""
Module managing the Wiki API requests
"""
import requests
from random import choice

class Wikipedia():
    """
    Class made to manage the requests to the API and return them.
    Methods:
    * get_api_request(lat, lng, user_search):
        This method returns the title of an event regarding the
        place the user has searched for. (ex: Paris - Prise de la
        Bastille)
        * Arguments:
            - lat : latitude of the searched place, generated by
            google maps.
            - lng : longitude of the searched place, generated by
            google maps.
            - user_search : parsed user input.
    * return_place_info(title):
        This method returns the information regarding the searched
        place via Wikipedia and its link.
        * Arguments:
            - title : Title of an event regarding the place the user
            has searched for. (ex: Prise de la Bastille)
    """
    def __init__(self):
        pass
    
    def get_api_request(self, lat, lng, user_search):
        """
        This method returns the title of an event regarding the
        place the user has searched for. (ex: Paris - Prise de la
        Bastille)
        * Arguments:
            - lat : latitude of the searched place, generated by
            google maps.
            - lng : longitude of the searched place, generated by
            google maps.
            - user_search : parsed user input.
        * Return:
            title : contains the title of an event regarding the
            place the user has searched for. (ex: Paris - Prise de la
            Bastille)
        """
        url = "https://fr.wikipedia.org/w/api.php"
        params = {"action": "query", "list": "geosearch", "gsradius": "10000",
                    "gscoord": f"{lat}|{lng}", "format": "json"}
        request = requests.get(url, params=params).json()
        tosearch = request["query"]["geosearch"]

        for event in tosearch:
            if event["title"] != "":
                tosearch = event
        if tosearch:
            title = tosearch["title"]
            return title
        return "Error"

    def return_place_info(self, title):
        """
        This method returns the information regarding the searched
        place via Wikipedia and its link.
        * Arguments:
            - title : Title of an event regarding the place the user
            has searched for. (ex: Prise de la Bastille)
        * Return:
            - bot_answer : contains the information of an event taken
            from Wikipedia + its Wikipedia link concatenated.
        """
        url = f"https://fr.wikipedia.org/api/rest_v1/page/summary/{title}"
        request = requests.get(url).json()
        place_info = request["extract"]
        link = request["content_urls"]["desktop"]["page"]
        bot_answer = place_info + "</br>" + f"<a href='{link}' style='color:white;'>[En savoir plus sur Wikipedia]</a>"
        return bot_answer